name: random
baseurl: /random
description: Pure Randomness in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+7-e603ec17-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
