name: random
baseurl: /random
description: Pure Randomness in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+6-e8c60753-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
