name: random
baseurl: /random
description: Pure Randomness in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+8-7c9e8346-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
