name: random
baseurl: /random
description: Random Generation for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.0+4-de371e3e-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
