name: random
baseurl: /random
description: Random Generation for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+1-fa3a4d6f-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
